"""Pydantic schemas for API request/response validation"""

from .auth import (
    LoginRequest,
    LoginResponse,
    UserResponse,
    DistrictResponse,
    DepartmentResponse,
    UserRole,
)
from .grievance import (
    GrievanceCreateRequest,
    GrievanceUpdateRequest,
    GrievanceResponse,
    GrievanceDetailResponse,
    GrievanceListResponse,
    GrievancePublicResponse,
    BulkUpdateRequest,
    BulkUpdateResponse,
    OTPResponse,
    OTPErrorResponse,
    JobStatusResponse,
    AttachmentResponse,
    AuditLogResponse,
    VerificationResponse,
    Language,
    Channel,
    GrievanceStatus,
    Priority,
    JobStatus,
    VerificationMethod,
    CitizenResponse,
    AuditAction,
    AttachmentType,
)
from .common import (
    ErrorResponse,
    HealthResponse,
    DatabaseHealthResponse,
    PaginationResponse,
    ValidationErrorDetail,
    HealthStatus,
)
from .empathy import (
    DistressLevel,
    DistressAnalysisRequest,
    DistressAnalysisResult,
    GrievanceSentimentResponse,
    EmpathyTemplateCreate,
    EmpathyTemplateResponse,
    DistressKeywordCreate,
    DistressKeywordResponse,
    Language as EmpathyLanguage,
)
from .resolution import (
    RootCause,
    InterventionResult,
    ResponseType,
    ActionStep,
    ActionExecuted,
    ApplyTemplateRequest,
    ClarificationAnswer,
    ClarificationSubmission,
    UpdateApplicationResultRequest,
    InterventionQuestionResponse,
    ResolutionTemplateResponse,
    RootCauseAnalysisResult,
    TemplateApplicationResult,
    ClarificationResult,
    RootCauseAnalysisResponse,
    TemplateApplicationResponse,
    TemplateListParams,
    QuestionListParams,
)
from .citizen_empowerment import (
    OptInChoice,
    TriggerType,
    InteractionType,
    Language as EmpowermentLanguage,
    OptInRequest,
    LevelUpRequest,
    RightEntryCreate,
    TriggerRequest,
    RightInfo,
    EmpowermentResponse,
    OptInResponse,
    RightEntryResponse,
    TriggerResponse,
    PreferenceResponse,
    InteractionLogResponse,
    ProactiveTriggerConfigResponse,
    RightsListResponse,
    InteractionsListResponse,
)
from .verifier import (
    VerificationResult,
    Badge,
    LeaderboardPeriod,
    QueueStatus,
    VerificationSubmitRequest,
    GrievanceQueueItem,
    VerificationQueueResponse,
    VerificationSubmitResponse,
    VerifierStatsResponse,
    LeaderboardEntry,
    LeaderboardResponse,
)

__all__ = [
    # Auth
    "LoginRequest",
    "LoginResponse",
    "UserResponse",
    "DistrictResponse",
    "DepartmentResponse",
    "UserRole",
    # Grievance
    "GrievanceCreateRequest",
    "GrievanceUpdateRequest",
    "GrievanceResponse",
    "GrievanceDetailResponse",
    "GrievanceListResponse",
    "GrievancePublicResponse",
    "BulkUpdateRequest",
    "BulkUpdateResponse",
    "OTPResponse",
    "OTPErrorResponse",
    "JobStatusResponse",
    "AttachmentResponse",
    "AuditLogResponse",
    "VerificationResponse",
    "Language",
    "Channel",
    "GrievanceStatus",
    "Priority",
    "JobStatus",
    "VerificationMethod",
    "CitizenResponse",
    "AuditAction",
    "AttachmentType",
    # Common
    "ErrorResponse",
    "HealthResponse",
    "DatabaseHealthResponse",
    "PaginationResponse",
    "ValidationErrorDetail",
    "HealthStatus",
    # Empathy
    "DistressLevel",
    "DistressAnalysisRequest",
    "DistressAnalysisResult",
    "GrievanceSentimentResponse",
    "EmpathyTemplateCreate",
    "EmpathyTemplateResponse",
    "DistressKeywordCreate",
    "DistressKeywordResponse",
    "EmpathyLanguage",
    # Resolution
    "RootCause",
    "InterventionResult",
    "ResponseType",
    "ActionStep",
    "ActionExecuted",
    "ApplyTemplateRequest",
    "ClarificationAnswer",
    "ClarificationSubmission",
    "UpdateApplicationResultRequest",
    "InterventionQuestionResponse",
    "ResolutionTemplateResponse",
    "RootCauseAnalysisResult",
    "TemplateApplicationResult",
    "ClarificationResult",
    "RootCauseAnalysisResponse",
    "TemplateApplicationResponse",
    "TemplateListParams",
    "QuestionListParams",
    # Citizen Empowerment
    "OptInChoice",
    "TriggerType",
    "InteractionType",
    "EmpowermentLanguage",
    "OptInRequest",
    "LevelUpRequest",
    "RightEntryCreate",
    "TriggerRequest",
    "RightInfo",
    "EmpowermentResponse",
    "OptInResponse",
    "RightEntryResponse",
    "TriggerResponse",
    "PreferenceResponse",
    "InteractionLogResponse",
    "ProactiveTriggerConfigResponse",
    "RightsListResponse",
    "InteractionsListResponse",
    # Verifier Portal
    "VerificationResult",
    "Badge",
    "LeaderboardPeriod",
    "QueueStatus",
    "VerificationSubmitRequest",
    "GrievanceQueueItem",
    "VerificationQueueResponse",
    "VerificationSubmitResponse",
    "VerifierStatsResponse",
    "LeaderboardEntry",
    "LeaderboardResponse",
]
