"""add_ml_training_tables_proper

Revision ID: dade9ecbca0b
Revises: 6e4f18e0c7cd
Create Date: 2025-11-25 14:33:41.428937+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dade9ecbca0b'
down_revision: Union[str, None] = '6e4f18e0c7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_clips',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('transcription_telugu', sa.Text(), nullable=False),
    sa.Column('transcription_english', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('language_detected', sa.String(length=10), nullable=False),
    sa.Column('contains_department_name', sa.Boolean(), nullable=False),
    sa.Column('departments_mentioned', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('extracted_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('transcription_length', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_clips_filename'), 'audio_clips', ['filename'], unique=False)
    op.create_table('message_templates',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('text_telugu', sa.Text(), nullable=False),
    sa.Column('text_english', sa.Text(), nullable=True),
    sa.Column('contains_department', sa.Boolean(), nullable=False),
    sa.Column('extracted_departments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('extracted_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('officer_designations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_category'), 'message_templates', ['category'], unique=False)
    op.create_index(op.f('ix_message_templates_template_id'), 'message_templates', ['template_id'], unique=True)
    op.create_table('department_keywords',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('subject_english', sa.String(length=200), nullable=False),
    sa.Column('subject_telugu', sa.String(length=200), nullable=True),
    sa.Column('keyword_english', sa.String(length=100), nullable=False),
    sa.Column('keyword_telugu', sa.String(length=100), nullable=True),
    sa.Column('sub_subjects', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_keywords_department_id'), 'department_keywords', ['department_id'], unique=False)
    op.create_index(op.f('ix_department_keywords_keyword_english'), 'department_keywords', ['keyword_english'], unique=False)
    op.create_index(op.f('ix_department_keywords_keyword_telugu'), 'department_keywords', ['keyword_telugu'], unique=False)
    op.create_table('lapse_cases',
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('lapse_category', sa.String(length=200), nullable=False),
    sa.Column('lapse_category_telugu', sa.String(length=200), nullable=True),
    sa.Column('lapse_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('officer_designation', sa.String(length=200), nullable=True),
    sa.Column('improper_percentage', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('total_cases_audited', sa.Integer(), nullable=True),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('source_audit', sa.String(length=200), nullable=False),
    sa.Column('audit_date', sa.String(length=20), nullable=True),
    sa.Column('mandal', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lapse_cases_department_id'), 'lapse_cases', ['department_id'], unique=False)
    op.create_index(op.f('ix_lapse_cases_district_id'), 'lapse_cases', ['district_id'], unique=False)
    op.create_index(op.f('ix_lapse_cases_lapse_category'), 'lapse_cases', ['lapse_category'], unique=False)
    op.create_index(op.f('ix_lapse_cases_lapse_type'), 'lapse_cases', ['lapse_type'], unique=False)
    op.create_index(op.f('ix_lapse_cases_source_audit'), 'lapse_cases', ['source_audit'], unique=False)
    op.create_table('officers',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('received', sa.Integer(), nullable=False),
    sa.Column('viewed', sa.Integer(), nullable=False),
    sa.Column('pending', sa.Integer(), nullable=False),
    sa.Column('redressed', sa.Integer(), nullable=False),
    sa.Column('improper_rate', sa.Float(), nullable=False),
    sa.Column('workload', sa.Integer(), nullable=False),
    sa.Column('viewed_ratio', sa.Float(), nullable=False),
    sa.Column('throughput', sa.Float(), nullable=False),
    sa.Column('dept_context', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officers_department_id'), 'officers', ['department_id'], unique=False)
    op.create_index(op.f('ix_officers_designation'), 'officers', ['designation'], unique=False)
    op.create_table('satisfaction_metrics',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('total_feedback', sa.Integer(), nullable=False),
    sa.Column('avg_satisfaction_5', sa.Float(), nullable=False),
    sa.Column('pct_satisfied', sa.Float(), nullable=False),
    sa.Column('dept_risk_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('relative_weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satisfaction_metrics_department_id'), 'satisfaction_metrics', ['department_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_satisfaction_metrics_department_id'), table_name='satisfaction_metrics')
    op.drop_table('satisfaction_metrics')
    op.drop_index(op.f('ix_officers_designation'), table_name='officers')
    op.drop_index(op.f('ix_officers_department_id'), table_name='officers')
    op.drop_table('officers')
    op.drop_index(op.f('ix_lapse_cases_source_audit'), table_name='lapse_cases')
    op.drop_index(op.f('ix_lapse_cases_lapse_type'), table_name='lapse_cases')
    op.drop_index(op.f('ix_lapse_cases_lapse_category'), table_name='lapse_cases')
    op.drop_index(op.f('ix_lapse_cases_district_id'), table_name='lapse_cases')
    op.drop_index(op.f('ix_lapse_cases_department_id'), table_name='lapse_cases')
    op.drop_table('lapse_cases')
    op.drop_index(op.f('ix_department_keywords_keyword_telugu'), table_name='department_keywords')
    op.drop_index(op.f('ix_department_keywords_keyword_english'), table_name='department_keywords')
    op.drop_index(op.f('ix_department_keywords_department_id'), table_name='department_keywords')
    op.drop_table('department_keywords')
    op.drop_index(op.f('ix_message_templates_template_id'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_category'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_audio_clips_filename'), table_name='audio_clips')
    op.drop_table('audio_clips')
    # ### end Alembic commands ###
